export const FETCHING_HERO_LIST = 'FETCHING_HERO_LIST';
export const FETCH_HERO_LIST_SUCCEED = 'FETCH_HERO_LIST_SUCCEED';
export const FETCH_HERO_LIST_FAILED = 'FETCH_HERO_LIST_FAILED';
export const RESET_HERO_LIST = 'RESET_HERO_LIST';
export const SORT_HERO_LIST = 'SORT_HERO_LIST';
